name: Run on metadata.json change

on:
  push:
    paths:
      - 'scenarios/metadata.json'
  workflow_dispatch:

permissions:
    contents: write

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
            repository: 'MicrosoftDocs/executable-docs'
            ref: naman-code  # replace with your branch name
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: Set git identity
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Run metadata.py
        run: python .github/workflows/metadata.py
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Updated localized metadata.json files"
          git push