name: Sync Markdown Files

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday
  workflow_dispatch:

permissions:
    contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout executable-docs
      uses: actions/checkout@v2
      with:
        repository: 'MicrosoftDocs/executable-docs'
        token: ${{ secrets.GITHUB_TOKEN }} # This line is added

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install PyGithub

    - name: Set git identity
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"

    - name: Sync markdown files
      run: python .github/workflows/sync.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Replace with the name of your secret

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Sync markdown files"
        git push